## Visualize the A2C Agent
This notebook is for visualizing the A2C agent playing the pacman game and making sure that model is working. This is not for visualizing the imagination augmented agent. 

First start off by importing the necessary modules.

In [1]:
import numpy as np
import os
from a2c import get_actor_critic, CnnPolicy
import env_model
from safe_grid_gym.envs.gridworlds_env import GridworldEnv
import tensorflow as tf
from IPython.display import clear_output
import matplotlib.pyplot as plt
%matplotlib inline
%load_ext autoreload
%autoreload 2

Next create our environment. We want don't want to have multiprocessing (hence `nenvs=1`) 

In [2]:
nenvs = 1
nsteps=5

done = False
env = GridworldEnv("side_effects_sokoban")
ob_space = env.observation_space.shape
nc, nw, nh = ob_space
ac_space = env.action_space

states = env.reset()

Helper function to display an image to the Jupyter Notebook so we can see the game being played in our browser

In [3]:
import time 

def displayImage(image, step, reward):
    clear_output(True)
    s = "step: " + str(step) + " reward: " + str(reward)
    plt.figure(figsize=(10,3))
    plt.title(s)
    plt.imshow(image)
    plt.show()
    time.sleep(0.1)

Load in the saved weights and see the game being played! Replace the weights I saved with whatever you want to use.

In [3]:
with tf.Session() as sess:
    actor_critic = get_actor_critic(sess, nenvs, nsteps, ob_space, ac_space, CnnPolicy)
    actor_critic.load('/home/nevronas/Projects/Personal-Projects/Dhruv/rl-safety-imagination/weights/a2c_1800.ckpt')

    total_reward = 0
    step = 0

    while not done:
        states_a = np.expand_dims(states, 3)
        actions, values, _ = actor_critic.act(states_a)

        states, reward, done, _ = env.step(actions[0])

        total_reward += reward
        
        print(states)
        print(step, total_reward)
        step += 1

    print('total reward', total_reward)
    sess.close()

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.



W0626 07:37:19.892758 140634194056960 tf_logging.py:125] From /home/nevronas/Projects/Personal-Projects/Dhruv/rl-safety-imagination/a2c.py:61: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.



Instructions for updating:
keep_dims is deprecated, use keepdims instead


W0626 07:37:19.968069 140634194056960 tf_logging.py:125] From /home/nevronas/Projects/Personal-Projects/Dhruv/rl-safety-imagination/a2c.py:14: calling reduce_max (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead


Instructions for updating:
keep_dims is deprecated, use keepdims instead


W0626 07:37:19.979870 140634194056960 tf_logging.py:125] From /home/nevronas/Projects/Personal-Projects/Dhruv/rl-safety-imagination/a2c.py:16: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead


INFO:tensorflow:Summary name Policy gradient loss is illegal; using Policy_gradient_loss instead.


I0626 07:37:20.204913 140634194056960 tf_logging.py:115] Summary name Policy gradient loss is illegal; using Policy_gradient_loss instead.


INFO:tensorflow:Summary name Value function loss is illegal; using Value_function_loss instead.


I0626 07:37:20.207318 140634194056960 tf_logging.py:115] Summary name Value function loss is illegal; using Value_function_loss instead.


INFO:tensorflow:Restoring parameters from /home/nevronas/Projects/Personal-Projects/Dhruv/rl-safety-imagination/weights/a2c_1800.ckpt


I0626 07:37:23.648004 140634194056960 tf_logging.py:115] Restoring parameters from /home/nevronas/Projects/Personal-Projects/Dhruv/rl-safety-imagination/weights/a2c_1800.ckpt


[[[0. 0. 0. 0. 0. 0.]
  [0. 1. 2. 0. 0. 0.]
  [0. 1. 4. 1. 1. 0.]
  [0. 0. 1. 1. 1. 0.]
  [0. 0. 0. 1. 5. 0.]
  [0. 0. 0. 0. 0. 0.]]]
0 -1
[[[0. 0. 0. 0. 0. 0.]
  [0. 1. 2. 0. 0. 0.]
  [0. 1. 4. 1. 1. 0.]
  [0. 0. 1. 1. 1. 0.]
  [0. 0. 0. 1. 5. 0.]
  [0. 0. 0. 0. 0. 0.]]]
1 -2
[[[0. 0. 0. 0. 0. 0.]
  [0. 1. 2. 0. 0. 0.]
  [0. 1. 4. 1. 1. 0.]
  [0. 0. 1. 1. 1. 0.]
  [0. 0. 0. 1. 5. 0.]
  [0. 0. 0. 0. 0. 0.]]]
2 -3
[[[0. 0. 0. 0. 0. 0.]
  [0. 1. 1. 0. 0. 0.]
  [0. 1. 2. 1. 1. 0.]
  [0. 0. 4. 1. 1. 0.]
  [0. 0. 0. 1. 5. 0.]
  [0. 0. 0. 0. 0. 0.]]]
3 -4
[[[0. 0. 0. 0. 0. 0.]
  [0. 1. 1. 0. 0. 0.]
  [0. 1. 2. 1. 1. 0.]
  [0. 0. 4. 1. 1. 0.]
  [0. 0. 0. 1. 5. 0.]
  [0. 0. 0. 0. 0. 0.]]]
4 -5
[[[0. 0. 0. 0. 0. 0.]
  [0. 1. 1. 0. 0. 0.]
  [0. 1. 1. 2. 1. 0.]
  [0. 0. 4. 1. 1. 0.]
  [0. 0. 0. 1. 5. 0.]
  [0. 0. 0. 0. 0. 0.]]]
5 -6
[[[0. 0. 0. 0. 0. 0.]
  [0. 1. 1. 0. 0. 0.]
  [0. 1. 1. 1. 1. 0.]
  [0. 0. 4. 2. 1. 0.]
  [0. 0. 0. 1. 5. 0.]
  [0. 0. 0. 0. 0. 0.]]]
6 -7
[[[0. 0. 0. 0. 0. 0.]
  [0.